### ISSUE TITLE
creation reference

### ISSUE THREAD

**Issue by fengdong110** [VUmcCGP/wisecondor#27]
HI :

How do you choose samples to create the reference ?  Choose to create  reference principle ?
Only chose the negative samples or random chose samples?

Thank you very much.

**Comment by dridk** [comment]
I create my reference with negative sample. 
You can test my reference , it is avaible here : https://github.com/dridk/ion-wisecondor/blob/master/data/reftable

**Comment by fengdong110** [comment]
Honored dridk:
    Thank you very much for your reply.
    Then I have another question, will the amount of negative samples impact the reference, I mean how many negative samples is enough for the reference? And the training samples for building reference contains a few positive samples may affect the reference or not?
    Thank you very much!
     Good luck and best wishes!

**Comment by dridk** [comment]
yes, it will probably affect the reference if you have positif sample . 
I have 16 negatif sample in my reference.

**Comment by fengdong110** [comment]
Honored dridk:
Thank you very much!

**Comment by rstraver** [comment]
Thanks for responding @dridk, I assume this issue is resolved.
