### ISSUE TITLE
question of procedure

### ISSUE THREAD

**Issue by fengdong110** [VUmcCGP/wisecondor#28]
I have a little problem:

gcc.py procedure :
“”lowessCurve = biostat.lowess(allX,allY,f=fVal, iter=iVal).tolist()“”

I want to know "lowessCurve" is correctedReads or like LOESS fit predicted value (P).
my friend said "lowessCurve" is correctedReads, but I do not think so. so thank you for your help.

**Comment by rstraver** [comment]
The `lowessCurve` variable you are referring to contains information on the modeled read depth values for 'predicting' them based on the GC content of a bin. 
The actual correction of the data happens in the bit after that:
```
for chrom in chroms:
	correctedSample[chrom] = []
		for bin in range(min(len(gcCount[chrom]),len(sample[chrom]))):
```

In the lines after, the actual read depth of a bin is 'corrected' by dividing its value by the expected value according to `lowessCurve`

If I understand you correctly, I'd say your description 

> like LOESS fit predicted value (P)

is the correct interpretation here, as the values are certainly not corrected yet.

**Comment by fengdong110** [comment]
Thank you very much for your reply.
What do you  mean correctedValue (correctedValue = sample[chrom][bin]/lowessCurve.pop(0))  is correctedReads ?

**Comment by rstraver** [comment]
`correctedValue = sample[chrom][bin]/lowessCurve.pop(0)`
contains one corrected value.

Basically, all bin read depth values are stored in a list and as the order remains unchanged, values are corrected one by one.

`correctedSample` contains the corrected values for all chromosomes, using a dictionary a list is kept per chromosome.
